name: Node.js CI

on:
  push:
    branches: main


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project       
        run: npm run build   
    
      - name: List contents of dist folder
        run: ls -alh dist/

      # - name: Upload build artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: artifact-file
      #     path: ./dist/
          
      # - name: Check the artifact files
      #   run: |
      #     ls -a 